// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: echo.proto

package apis

import (
	context "context"
	fmt "fmt"
	runtime "github.com/atotto/grpc-gateway-httpclient/runtime"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
	http "net/http"
	url "net/url"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func NewEchoServiceHttpClient(client *http.Client, url *url.URL) *EchoServiceHttpClient {
	return &EchoServiceHttpClient{Client: &runtime.Client{Client: client}, URL: *url}
}

type EchoServiceHttpClient struct {
	Client *runtime.Client
	URL    url.URL
}

func (c *EchoServiceHttpClient) Echo(ctx context.Context, req *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	var err error
	res := &EchoResponse{}
	u := c.URL
	u.Path = "/echo"
	err = c.Client.Post(ctx, u.String(), req, res)
	return res, err
}
